// <auto-generated />
namespace Vidly.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class makegenreIdnotnull : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(makegenreIdnotnull));
        
        string IMigrationMetadata.Id
        {
            get { return "202004281138480_makegenreIdnotnull"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
